#!/bin/bash

# read the email address to notify from the config file
EMAIL=`cat ~/.notify | grep -i email | egrep -o "[a-zA-Z0-9]+@[a-zA-Z.]+"`
SMS=`cat ~/.notify | grep -i sms | egrep -o "[0-9]+@[a-zA-Z.]+"`
USE_EMAIL=

# used in functions below
COMMAND=

function usage
{
	echo "usage:	`basename $0` command_to_run"
}

# run the input command 
# redirecting stderr to stdout 
# and notify via mail when finished
function notify
{
  if [ "$USE_EMAIL" -eq "1" ]; then
    $COMMAND 2>&1 | tee >(mail -s "Command Finished: $COMMAND" "$EMAIL") 
  else
    $COMMAND 2>&1 | head -c 100 | tee >(mail -s "Command Finished" "$SMS")
  fi
}

while [ "$1" != "" ]; do
	case $1 in 
    -e|--email )       
    USE_EMAIL=1
    ;;
		-h|--help ) 	
    usage
    exit
    ;;
		* )			        
    COMMAND=$@
    notify
    exit
	esac
	shift
done
